# Generated by Django 4.0.5 on 2022-06-21 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('id_atm', models.CharField(blank=True, max_length=30)),
                ('cd_atm', models.CharField(blank=True, max_length=30)),
                ('ds_atm', models.CharField(blank=True, max_length=30)),
                ('ds_logradouro', models.CharField(blank=True, max_length=30)),
                ('nr_logradouro', models.CharField(blank=True, max_length=30)),
                ('ds_bairro', models.CharField(blank=True, max_length=30)),
                ('ds_cidade', models.CharField(blank=True, max_length=30)),
                ('ds_uf', models.CharField(blank=True, max_length=30)),
                ('ds_cep', models.CharField(blank=True, max_length=30)),
                ('nr_long', models.CharField(blank=True, max_length=30)),
                ('nr_lat', models.CharField(blank=True, max_length=30)),
                ('id_status', models.CharField(blank=True, max_length=30)),
                ('ds_horario_func', models.CharField(blank=True, max_length=100)),
                ('fg_acessivel', models.CharField(blank=True, max_length=30)),
                ('ds_segmento', models.CharField(blank=True, max_length=30)),
                ('nr_segmento', models.CharField(blank=True, max_length=30)),
                ('vl_cedula1', models.CharField(blank=True, max_length=30)),
                ('vl_cedula2', models.CharField(blank=True, max_length=30)),
                ('id_moedaestrang', models.CharField(blank=True, max_length=30)),
                ('id_saquecom', models.CharField(blank=True, max_length=30)),
                ('id_recicladora', models.CharField(blank=True, max_length=30)),
                ('id_pgtocontas', models.CharField(blank=True, max_length=30)),
                ('horario_inicial', models.CharField(blank=True, max_length=30)),
                ('horario_final', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
